Repository Simperfy/COVID-19-PH-DOH, pull requests merged in 2020-08, with the labels that each got.

#2 Dauntlessdev
  lib/main.dart
  lib/services/api_path.dart
  lib/services/database.dart
  lib/services/network_helper.dart
  lib/widgets/summary_widget/sub_recovered.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#6 added model and db methods for record and cases
  lib/main.dart
  lib/model/case.dart
  lib/model/case_timeline.dart
  lib/model/record.dart
  lib/model/recordList.dart
  lib/model/region.dart
  lib/model/regionList.dart
  lib/model/summary.dart
  lib/services/database.dart
  lib/services/network_helper.dart
Labels: enhancement

#5 ADDED: daily cases charts
  lib/main.dart
  lib/ui/views/home/home_view.dart
  lib/util/constants.dart
  lib/widgets/simple_chart_widget/simple_chart_widget.dart
  lib/widgets/simple_chart_widget/time_series.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#8 ADDED: Dynamic Charts & Summary
  lib/ui/views/home/home_view.dart
  lib/widgets/simple_chart_widget/time_series.dart
  lib/widgets/summary_widget/base/summary_base.dart
  lib/widgets/summary_widget/main/main_text/main_text_count.dart
  lib/widgets/summary_widget/main/main_text/main_text_label.dart
  lib/widgets/summary_widget/main/main_text_count.dart
  lib/widgets/summary_widget/main/main_total_cases.dart
  lib/widgets/summary_widget/sub/sub_active_cases.dart
  lib/widgets/summary_widget/sub/sub_died.dart
  lib/widgets/summary_widget/sub/sub_recovered.dart
  lib/widgets/summary_widget/sub/sub_text/sub_text_count.dart
  lib/widgets/summary_widget/sub/sub_text/sub_text_label.dart
  lib/widgets/summary_widget/sub/sub_text_count.dart
  lib/widgets/summary_widget/summary_widget.dart
  lib/widgets/timeline_widget/time_series.dart
  lib/widgets/timeline_widget/timeline_widget.dart
Labels: enhancement

#10 FIXED: Summary Texts Overflow
  lib/widgets/summary_widget/main/main_text/main_text_count.dart
  lib/widgets/summary_widget/main/main_total_cases.dart
  lib/widgets/summary_widget/sub/sub_text/sub_text_label.dart
Labels: bug fixes

#11 ADDED: (Feature) Dynamic Top regions 🔥
  lib/ui/views/home/home_view.dart
  lib/widgets/base/abstracts/abstract_home_view_card.dart
  lib/widgets/search_bar_widget/search_bar_widget.dart
  lib/widgets/summary_widget/base/abstracts/abstract_summary.dart
  lib/widgets/summary_widget/base/summary_base.dart
  lib/widgets/summary_widget/main/main_text/main_text_count.dart
  lib/widgets/summary_widget/main/main_text/main_text_label.dart
  lib/widgets/summary_widget/main/main_total_cases.dart
  lib/widgets/summary_widget/sub/sub_active_cases.dart
  lib/widgets/summary_widget/sub/sub_died.dart
  lib/widgets/summary_widget/sub/sub_recovered.dart
  lib/widgets/summary_widget/sub/sub_text/sub_text_count.dart
  lib/widgets/summary_widget/sub/sub_text/sub_text_label.dart
  lib/widgets/summary_widget/summary_widget.dart
  lib/widgets/timeline_widget/concretes/timeline_card.dart
  lib/widgets/timeline_widget/timeline_chart_widget/time_series.dart
  lib/widgets/timeline_widget/timeline_chart_widget/timeline_chart_widget.dart
  lib/widgets/timeline_widget/timeline_widget.dart
  lib/widgets/top_regions_widget/concretes/top_regions_card.dart
  lib/widgets/top_regions_widget/top_regions_widget.dart
Labels: enhancement

#16 ADDED: Facilities page & Refactored frontend with MVVM Stacked Architecture 🔥 🔥 🔥
  lib/main.dart
  lib/ui/pages/views/facilities_view/facilities_view.dart
  lib/ui/pages/views/facilities_view/facilities_view_model.dart
  lib/ui/pages/views/home_view/home_view.dart
  lib/ui/pages/views/home_view/home_view_model.dart
  lib/ui/partials/base/abstracts/abstract_home_view_card.dart
  lib/ui/partials/views/summary_view/base/abstracts/abstract_summary.dart
  lib/ui/partials/views/summary_view/main/main_text/main_text_count.dart
  lib/ui/partials/views/summary_view/main/main_text/main_text_label.dart
  lib/ui/partials/views/summary_view/main/main_total_cases.dart
  lib/ui/partials/views/summary_view/sub/sub_active_cases.dart
  lib/ui/partials/views/summary_view/sub/sub_died.dart
  lib/ui/partials/views/summary_view/sub/sub_recovered.dart
  lib/ui/partials/views/summary_view/sub/sub_text/sub_text_count.dart
  lib/ui/partials/views/summary_view/sub/sub_text/sub_text_label.dart
  lib/ui/partials/views/summary_view/summary_view.dart
  lib/ui/partials/views/summary_view/summary_view_model.dart
  lib/ui/partials/views/timeline_view/concretes/timeline_card.dart
  lib/ui/partials/views/timeline_view/timeline_view.dart
  lib/ui/partials/views/timeline_view/timeline_view_model.dart
  lib/ui/partials/views/top_regions_view/concretes/top_regions_card.dart
  lib/ui/partials/views/top_regions_view/top_regions_view.dart
  lib/ui/partials/views/top_regions_view/top_regions_view_model.dart
  lib/ui/view_manager.dart
  lib/ui/view_manager_model.dart
  lib/ui/views/home/home_view.dart
  lib/ui/widgets/search_bar_widget/search_bar_widget.dart
  lib/ui/widgets/search_bar_widget/search_field.dart
  lib/ui/widgets/timeline_chart_widget/time_series.dart
  lib/ui/widgets/timeline_chart_widget/timeline_chart_widget.dart
  lib/widgets/bottom_navbar_widget/bottom_navbar_widget.dart
  lib/widgets/summary_widget/summary_widget.dart
  lib/widgets/timeline_widget/timeline_widget.dart
  lib/widgets/top_regions_widget/top_regions_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#31 ADDED: mock test for hospital database
  lib/model/hospital.dart
  lib/model/hospital_list.dart
  test/hospital_database_test.dart
Labels: enhancement

#32 Added facilities view ui
  lib/main.dart
  lib/ui/pages/views/facilities_view/facilities_view.dart
  lib/ui/view_manager.dart
  lib/util/constants.dart
  pubspec.yaml
Labels: enhancement

#33 HOTFIX: fixed UI overflows
  lib/main.dart
  lib/ui/partials/views/facilities_summary_view/facilities_summary_view.dart
  lib/ui/partials/views/search_bar_view/search_bar_view.dart
  lib/ui/view_manager.dart
  lib/ui/view_manager_model.dart
  lib/util/helper.dart
  lib/util/size_config.dart
  pubspec.lock
  pubspec.yaml
Labels: HOTFIX

#35 Refactored: HospitalSummary model and HospitalDb test
  lib/model/hospital_summary.dart
  test/hospital_database_test.dart
Labels: enhancement

#37 Feature ci
  .github/workflows/dart.yml
Labels: enhancement

#36 ADDED: Inital test for UI
  pubspec.lock
  pubspec.yaml
  test/frontend/partials/views/summary_view_test.dart
  test/frontend/partials/views/timeline_view_test.dart
  test/frontend/partials/views/top_regions_view_test.dart
Labels: enhancement

#38 Feature facilities view func
  lib/ui/pages/views/facilities_view/facilities_view.dart
  lib/ui/pages/views/facilities_view/facilities_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#39 Optimized CI
  .github/workflows/dart.yml
  lib/model/hospital_summary.dart
  lib/ui/pages/views/home_view/home_view_model.dart
  lib/util/helper.dart
  test/frontend/partials/views/timeline_view_test.dart
Labels: enhancement

#41 FEATURE: Dynamic facilities page 🔨
  lib/model/hospital_summary.dart
  lib/services/api_path.dart
  lib/services/hospital_database.dart
  lib/services/record_database.dart
  lib/ui/pages/views/facilities_view/facilities_view.dart
  lib/ui/pages/views/facilities_view/facilities_view_model.dart
  lib/ui/partials/views/facilities_summary_view/facilities_summary_view.dart
  lib/ui/partials/views/facilities_summary_view/facilities_summary_view_model.dart
  lib/ui/partials/views/search_bar_view/_delegates/_base/search_bar_delegate_base.dart
  lib/ui/partials/views/search_bar_view/_delegates/facilities_search_bar_delegate.dart
  lib/ui/partials/views/search_bar_view/_delegates/home_search_bar_delegate.dart
  lib/ui/partials/views/search_bar_view/search_bar_view.dart
  lib/ui/partials/views/top_regions_view/top_regions_view_model.dart
  lib/ui/view_manager.dart
  lib/ui/view_manager_model.dart
  lib/ui/widgets/facilities_widgets/facilities_details_row.dart
  lib/ui/widgets/facilities_widgets/facilitites_title.dart
  lib/util/constants.dart
  lib/util/hospital_list.dart
  lib/util/region_list.dart
  lib/util/size_config.dart
Labels: enhancement

#42 UPDATED: Interface of Cards & summary card
  lib/ui/pages/views/facilities_view/facilities_view.dart
  lib/ui/pages/views/home_view/home_view.dart
  lib/ui/partials/base/abstracts/abstract_home_view_card.dart
  lib/ui/partials/views/search_bar_view/search_bar_view.dart
  lib/ui/partials/views/summary_view/base/abstracts/abstract_summary.dart
  lib/ui/partials/views/summary_view/main/main_text/main_text_count.dart
  lib/ui/partials/views/summary_view/main/main_text/main_text_label.dart
  lib/ui/partials/views/summary_view/main/main_total_cases.dart
  lib/ui/partials/views/summary_view/sub/sub_active_cases.dart
  lib/ui/partials/views/summary_view/sub/sub_died.dart
  lib/ui/partials/views/summary_view/sub/sub_recovered.dart
  lib/ui/partials/views/summary_view/sub/sub_text/sub_text_count.dart
  lib/ui/partials/views/summary_view/sub/sub_text/sub_text_label.dart
  lib/ui/partials/views/timeline_view/concretes/timeline_card.dart
  lib/ui/partials/views/top_regions_view/concretes/top_regions_card.dart
  lib/ui/view_manager.dart
  lib/ui/widgets/timeline_chart_widget/time_series.dart
  lib/ui/widgets/timeline_chart_widget/timeline_chart_widget.dart
  lib/util/constants.dart
  lib/util/helper.dart
  lib/util/size_config.dart
  test/frontend/partials/views/summary_view_test.dart
  test/frontend/partials/views/timeline_view_test.dart
  test/frontend/partials/views/top_regions_view_test.dart
Labels: enhancement

#43 FEATURE: Responsive HomeView & Facilitites View
  lib/ui/pages/views/facilities_view/facilities_view.dart
  lib/ui/partials/views/facilities_summary_view/facilities_summary_view.dart
  lib/ui/partials/views/search_bar_view/search_bar_view.dart
  lib/ui/partials/views/summary_view/base/abstracts/abstract_summary.dart
  lib/ui/partials/views/summary_view/main/main_text/main_text_count.dart
  lib/ui/partials/views/summary_view/main/main_text/main_text_label.dart
  lib/ui/partials/views/summary_view/sub/sub_text/sub_text_count.dart
  lib/ui/partials/views/summary_view/sub/sub_text/sub_text_label.dart
  lib/ui/partials/views/timeline_view/concretes/timeline_card.dart
  lib/ui/partials/views/top_regions_view/top_regions_view.dart
  lib/ui/partials/views/top_regions_view/top_regions_view_model.dart
  lib/ui/view_manager.dart
  lib/ui/view_manager_model.dart
  lib/ui/widgets/facilities_widgets/facilities_details_row.dart
  lib/ui/widgets/facilities_widgets/facilitites_title.dart
  lib/ui/widgets/timeline_chart_widget/timeline_chart_widget.dart
  lib/util/constants.dart
  lib/util/size_config.dart
Labels: enhancement

#45 HOTFIX: Hospital view error when searching hospitals with symbols
  lib/services/api_path.dart
  lib/services/hospital_database.dart
Labels: HOTFIX

#46 RE: Set meter color to grey if both value is zero
  lib/ui/widgets/facilities_widgets/facilities_details_row.dart
Labels: documentation

#47 added very basic tests for facilities widgets
  test/backend/hospital_database_test.dart
  test/backend/record_database_test.dart
  test/backend/region_database_test.dart
  test/backend/summary_database_test.dart
  test/backend/timeline_database_test.dart
  test/frontend/widgets/facilities_details_row_test.dart
  test/frontend/widgets/facilities_title_test.dart
Labels: enhancement

#48 Feature: Dummy maps
  lib/ui/partials/views/maps_view/_CaseCoordinates.dart
  lib/ui/partials/views/maps_view/maps_view.dart
  lib/ui/partials/views/maps_view/maps_view_model.dart
  lib/ui/view_manager.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#44 RELEASE: v0.2.0 🎉🎉🎉
  README.md
  lib/ui/view_manager.dart
Labels: Release, documentation, enhancement
